version: "2"
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    # command: sh -c "gunicorn -w 4 flaskr:app -b 0.0.0.0:5000 --access-logfile '-' --error-logfile '-'"
    # command: sh -c "ls"
    ports:
      - "8200:5000"
    volumes:
      - .:/app
    env_file: .env
    environment:
      - POSTGRES_URL

    extra_hosts:
      - "host.docker.internal:host-gateway"
