name: Deploy to fly.io and create version
on:
  # push:
    # branches:
      # - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WITH_V: true
  DEFAULT_BUMP: patch
  MAJOR_STRING_TOKEN: "release:"
  MINOR_STRING_TOKEN: "feat:"
  PATCH_STRING_TOKEN: "fix:"
  NONE_STRING_TOKEN: "none:"

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.61.0


  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
